# Generated by Django 5.1.1 on 2025-03-23 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_discovery', models.TextField(blank=True, default='', null=True)),
                ('accident_date', models.TextField(blank=True, default='', null=True)),
                ('investigating_body', models.CharField(default='', max_length=255)),
                ('accident_description', models.TextField(default='')),
                ('inspection_time', models.TextField(blank=True, null=True)),
                ('accident_location', models.CharField(blank=True, max_length=255, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='local', max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('typeAccident', models.CharField(blank=True, max_length=100, null=True)),
                ('resulting_damages', models.TextField(blank=True, null=True)),
                ('causes_of_fire', models.TextField(blank=True, null=True)),
                ('category_accident', models.CharField(choices=[('fireAccident', 'Fire Accident'), ('accident', 'Accident')], default='accident', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('accident_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('sampleType', models.CharField(blank=True, max_length=255, null=True)),
                ('sampleNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Placeoflifting', models.CharField(blank=True, max_length=255, null=True)),
                ('metodeIifting', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='local', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('accident_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='forensicapp.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('section_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('action', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='local', max_length=50)),
                ('isHidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forensicapp.incident')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('form_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('isChemistryLab', models.BooleanField(default=False)),
                ('isWeaponsLab', models.BooleanField(default=False)),
                ('isForensicLab', models.BooleanField(default=False)),
                ('isCriminalPrint', models.BooleanField(default=False)),
                ('isDNALab', models.BooleanField(default=False)),
                ('isCriminalElectronic', models.BooleanField(default=False)),
                ('status', models.CharField(default='local', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_forms', to='forensicapp.incident')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
