# Generated by Django 5.1.1 on 2025-03-16 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirePlaceDescribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_time', models.TextField(default='', null=True, verbose_name='الوقت')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('incident_date', models.DateField(default=django.utils.timezone.now)),
                ('request_authority', models.CharField(default='', max_length=255)),
                ('inspection_place', models.CharField(default='', max_length=255)),
                ('fire_place', models.TextField(blank=True, null=True)),
                ('damage', models.TextField(blank=True, null=True)),
                ('fire_reason', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigative_body', models.CharField(default='', max_length=255, verbose_name='الجهة التحقيقية')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('inspection_time', models.TextField(default='', null=True, verbose_name='الوقت')),
                ('incident_location', models.CharField(default='', max_length=500, verbose_name='مكان الحادث')),
                ('incident_type', models.CharField(default='', max_length=255, verbose_name='نوع الحادث')),
                ('incident_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحادث')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الحادث')),
                ('method', models.TextField(blank=True, null=True, verbose_name='الطريقة')),
                ('procedure', models.TextField(blank=True, null=True, verbose_name='الاجراءات المتخذة')),
            ],
        ),
        migrations.CreateModel(
            name='MapDescribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FireEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='رقم الاثر')),
                ('Typeofevidence', models.CharField(default='', max_length=255, verbose_name='نوع الاثر')),
                ('place', models.TextField(blank=True, null=True, verbose_name='مكان الرفع')),
                ('waytosave', models.TextField(blank=True, null=True, verbose_name='طريقة الرفع')),
                ('fire_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forensicapp.fireplacedescribtion', verbose_name='الحادث')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='رقم الاثر')),
                ('Typeofevidence', models.CharField(default='', max_length=255, verbose_name='نوع الاثر')),
                ('place', models.TextField(blank=True, null=True, verbose_name='مكان الرفع')),
                ('waytosave', models.TextField(blank=True, null=True, verbose_name='طريقة الرفع')),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forensicapp.incident', verbose_name='الحادث')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('action', models.TextField(blank=True, null=True)),
                ('state', models.CharField(default='', max_length=255)),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forensicapp.incident')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الكشف')),
                ('request_authority', models.CharField(default='', max_length=255, verbose_name='الجهة التحقيقية')),
                ('incident', models.TextField(blank=True, null=True, verbose_name='الحادث')),
                ('count', models.IntegerField(default=1)),
                ('crime_lab', models.BooleanField(default=False, verbose_name='مختبر الجريمة')),
                ('weapon_lab', models.BooleanField(default=False, verbose_name='مختبر الأسلحة')),
                ('chemistry_lab', models.BooleanField(default=False, verbose_name='مختبر الكيمياء')),
                ('dna_lab', models.BooleanField(default=False, verbose_name='مختبر DNA')),
                ('cyber_crime_lab', models.BooleanField(default=False, verbose_name='مختبر الجرائم الإلكترونية')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='forensicapp.evidence')),
                ('incident_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_details', to='forensicapp.incident')),
            ],
        ),
    ]
