# Generated by Django 5.1.1 on 2025-01-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_name', models.CharField(max_length=255)),
                ('photographer_name', models.CharField(max_length=255)),
                ('practitioner_name', models.CharField(max_length=255)),
                ('investigator_name', models.CharField(max_length=255)),
                ('head_of_investigation_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DamageDescribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('Typeofevidence', models.CharField(max_length=255)),
                ('place', models.TextField()),
                ('waytosave', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FirePlaceDescribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FireReasonDescribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField()),
                ('request_authority', models.CharField(max_length=255)),
                ('incident_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionFormEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('crime_lab', models.BooleanField(default=False, verbose_name='مختبر الجريمة')),
                ('weapon_lab', models.BooleanField(default=False, verbose_name='مختبر الأسلحة')),
                ('chemistry_lab', models.BooleanField(default=False, verbose_name='مختبر الكيمياء')),
                ('dna_lab', models.BooleanField(default=False, verbose_name='مختبر DNA')),
                ('cyber_crime_lab', models.BooleanField(default=False, verbose_name='مختبر الجرائم الإلكترونية')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='forensicapp.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigative_body', models.CharField(max_length=255)),
                ('inspection_date', models.DateField()),
                ('inspection_time', models.TimeField()),
                ('incident_location', models.CharField(max_length=500)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('procedure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forensicapp.proceduretaken')),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='procedure_taken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='forensicapp.proceduretaken'),
        ),
    ]
