# Generated by Django 5.1.1 on 2025-03-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='accident_Id',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='form_id',
        ),
    ]
