# Generated by Django 5.1.1 on 2025-03-16 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireevidence',
            name='fire_incident',
        ),
        migrations.DeleteModel(
            name='MapDescribtion',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_location',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='investigative_body',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='procedure',
        ),
        migrations.AddField(
            model_name='incident',
            name='accident_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='accident_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='accident_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='category_accident',
            field=models.CharField(choices=[('fireAccident', 'Fire Accident'), ('accident', 'Accident')], default='accident', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='causes_of_fire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_discovery',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='investigating_body',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resulting_damages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='typeAccident',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='inspection_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FireEvidence',
        ),
        migrations.DeleteModel(
            name='FirePlaceDescribtion',
        ),
    ]
