# Generated by Django 5.1.1 on 2025-02-01 07:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0002_mapdescribtion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='procedure_taken',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='procedure',
        ),
        migrations.AddField(
            model_name='incident',
            name='evidences',
            field=models.ManyToManyField(related_name='incidents', to='forensicapp.evidence'),
        ),
        migrations.AddField(
            model_name='incident',
            name='procedure_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='forensicapp.proceduretaken'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='inspection_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 1, 10, 16, 39, 539170)),
        ),
        migrations.AlterField(
            model_name='mapdescribtion',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapdescribtion',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
