# Generated by Django 5.1.1 on 2025-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0002_remove_evidence_accident_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionform',
            name='isChemistryLab',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspectionform',
            name='isWeaponsLab',
            field=models.BooleanField(default=True),
        ),
    ]
