# Generated by Django 5.1.1 on 2025-03-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0002_remove_fireevidence_fire_incident_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionform',
            old_name='inspection_date',
            new_name='inspection_time',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='request_authority',
            new_name='investigating_body',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='incident',
            new_name='typeAccident',
        ),
    ]
