# Generated by Django 5.1.1 on 2025-03-18 05:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0003_rename_inspection_date_inspectionform_inspection_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='state',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='Typeofevidence',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='number',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='place',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='waytosave',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='chemistry_lab',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='count',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='crime_lab',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='cyber_crime_lab',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='dna_lab',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='incident_obj',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='inspection_time',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='investigating_body',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='typeAccident',
        ),
        migrations.RemoveField(
            model_name='inspectionform',
            name='weapon_lab',
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forensicapp.incident'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='forensicapp.incident'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evidence',
            name='method_lifting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='place_of_lifting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sample_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sample_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='status',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_forms', to='forensicapp.incident'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='is_chemistry_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='is_criminal_electronic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='is_criminal_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='is_dna_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='is_forensic_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='is_weapons_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='status',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
