# Generated by Django 5.1.1 on 2025-02-01 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0003_remove_evidence_procedure_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='inspection_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 1, 10, 24, 10, 989133)),
        ),
    ]
