# Generated by Django 5.1.1 on 2025-02-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0004_alter_incident_inspection_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='procedure_taken',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complainant_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='head_of_investigation_name',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='investigator_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='photographer_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='practitioner_name',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='evidences',
        ),
        migrations.AddField(
            model_name='complaint',
            name='action',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forensicapp.incident'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='incident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forensicapp.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='procedure',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='inspection_time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='ProcedureTaken',
        ),
    ]
