# Generated by Django 5.1.1 on 2025-03-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0004_remove_complaint_section_id_remove_complaint_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionform',
            old_name='form',
            new_name='form_id',
        ),
    ]
