# Generated by Django 5.1.1 on 2025-03-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0005_rename_form_inspectionform_form_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='is_hidden',
            new_name='isHidden',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='method_lifting',
            new_name='Placeoflifting',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='place_of_lifting',
            new_name='metodeIifting',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='sample_number',
            new_name='sampleNumber',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='sample_type',
            new_name='sampleType',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='is_chemistry_lab',
            new_name='isChemistryLab',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='is_criminal_electronic',
            new_name='isCriminalElectronic',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='is_criminal_print',
            new_name='isCriminalPrint',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='is_dna_lab',
            new_name='isDNALab',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='is_forensic_lab',
            new_name='isForensicLab',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='is_weapons_lab',
            new_name='isWeaponsLab',
        ),
        migrations.RenameField(
            model_name='inspectionform',
            old_name='user',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='accident',
        ),
        migrations.AddField(
            model_name='evidence',
            name='accident_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='forensicapp.incident'),
        ),
    ]
