# Generated by Django 5.1.1 on 2025-02-10 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0005_remove_incident_procedure_taken_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DamageDescribtion',
        ),
        migrations.DeleteModel(
            name='FireReasonDescribtion',
        ),
        migrations.RemoveField(
            model_name='fireplacedescribtion',
            name='description',
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='damage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='fire_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='fire_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='inspection_place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='inspection_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='procedures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fireplacedescribtion',
            name='request_authority',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='chemistry_lab',
            field=models.BooleanField(default=False, verbose_name='مختبر الكيمياء'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='crime_lab',
            field=models.BooleanField(default=False, verbose_name='مختبر الجريمة'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='cyber_crime_lab',
            field=models.BooleanField(default=False, verbose_name='مختبر الجرائم الإلكترونية'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='dna_lab',
            field=models.BooleanField(default=False, verbose_name='مختبر DNA'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='forensicapp.evidence'),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='weapon_lab',
            field=models.BooleanField(default=False, verbose_name='مختبر الأسلحة'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='Typeofevidence',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='waytosave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='inspection_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='investigative_body',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionform',
            name='incident_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionform',
            name='inspection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inspectionform',
            name='request_authority',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mapdescribtion',
            name='color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mapdescribtion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapdescribtion',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='InspectionFormEvidence',
        ),
    ]
