# Generated by Django 5.1.1 on 2025-03-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0006_rename_is_hidden_complaint_ishidden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='accident_id',
            new_name='accident_Id',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='user',
            new_name='userId',
        ),
    ]
