# Generated by Django 5.1.1 on 2025-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0006_delete_damagedescribtion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
