# Generated by Django 5.1.1 on 2025-02-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0007_incident_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
