# Generated by Django 5.1.1 on 2025-02-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0008_incident_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionform',
            old_name='incident_details',
            new_name='incident',
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='incident_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_forms', to='forensicapp.incident'),
        ),
    ]
