# Generated by Django 5.1.1 on 2025-02-10 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0009_rename_incident_details_inspectionform_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionform',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
