# Generated by Django 5.1.1 on 2025-02-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0011_inspectionformdetails_inspectionformlabs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionformlabs',
            name='inspection_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='forensicapp.inspectionformdetails'),
        ),
    ]
