# Generated by Django 5.1.1 on 2025-02-12 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0012_alter_inspectionformlabs_inspection_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionformlabs',
            name='inspection_details',
        ),
        migrations.RemoveField(
            model_name='inspectionformlabs',
            name='evidence',
        ),
        migrations.CreateModel(
            name='InspectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('request_authority', models.CharField(default='', max_length=255)),
                ('incident', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=1)),
                ('crime_lab', models.BooleanField(default=False, verbose_name='مختبر الجريمة')),
                ('weapon_lab', models.BooleanField(default=False, verbose_name='مختبر الأسلحة')),
                ('chemistry_lab', models.BooleanField(default=False, verbose_name='مختبر الكيمياء')),
                ('dna_lab', models.BooleanField(default=False, verbose_name='مختبر DNA')),
                ('cyber_crime_lab', models.BooleanField(default=False, verbose_name='مختبر الجرائم الإلكترونية')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='forensicapp.evidence')),
                ('incident_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_details', to='forensicapp.incident')),
            ],
        ),
        migrations.DeleteModel(
            name='InspectionFormDetails',
        ),
        migrations.DeleteModel(
            name='InspectionFormLabs',
        ),
    ]
